### ISSUE TITLE
压缩密码

### ISSUE THREAD

**Issue by WangChongwen-me** [k8gege/Ladon#59]
请问Ladon7.0.rar压缩密码是什么，需要花钱买的吗（不知道在这里提问对不对。。）

**Comment by k8gege** [comment]
压缩包上有

**Comment by WangChongwen-me** [comment]
麻烦可以细说下吗，我输入提示内容LadonGUI.exe不对













在 2021-11-12 01:03:34，"k8gege" ***@***.***> 写道：

压缩包上有

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DarkAngel415** [comment]
密码多少？

**Comment by k8gege** [comment]
K8哥哥's BLOG
    http://qqhack8.blog.163.com

**Comment by DarkAngel415** [comment]
是lssue吗 Dark angel Dark angel ***@***.*** 签名由 网易邮箱大师 定制 在2021年12月08日 17:18，k8gege 写道： K8哥哥's BLOG http://qqhack8.blog.163.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DarkAngel415** [comment]
Hello, the password is incorrect. Dark angel Dark angel ***@***.*** 签名由 网易邮箱大师 定制 在2021年12月08日 17:27，Dark angel Dark angel 写道： 是lssue吗 Dark angel Dark angel ***@***.*** 签名由 网易邮箱大师 定制 在2021年12月08日 17:18，k8gege 写道： K8哥哥's BLOG http://qqhack8.blog.163.com — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by F6JO** [comment]
密码是个啥，压缩包上没有啊
![image](https://user-images.githubusercontent.com/64877810/148408482-81873438-d5dd-4f1a-92ad-88caa0bec4ef.png)

**Comment by sunpx3** [comment]
> 

密码: k8gege.org

**Comment by xingyun13** [comment]
为什么会有后门
